site_name: نیکل | خلاصه کتاب

theme:
    name: material
    language: fa
    features:
      - navigation.top
      - navigation.tracking
      - navigation.instant
      - navigation.instant.progress
      - toc.follow

    palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: "#"

plugins:
  - literate-nav:
      nav_file: summary.md
  - search
  - roamlinks
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://sajadafaghiy.github.io
  generator: false

extra_css:
  - css/extra.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
